-- Additive voice worker and browser-admission authority. Legacy Call/Utterance remain readable.
ALTER TYPE "Speaker" ADD VALUE IF NOT EXISTS 'HUMAN';
CREATE TYPE "VoiceTransport" AS ENUM ('LIVEKIT');
CREATE TYPE "VoiceSessionState" AS ENUM ('STARTING','ACTIVE','RECOVERY_REQUIRED','ENDED','FAILED');
CREATE TYPE "VoiceOwnershipMode" AS ENUM ('AI','HUMAN');
CREATE TYPE "VoiceAdmissionState" AS ENUM ('ISSUED','CONNECTING','ACTIVE','REVOKING','REVOKED','EXPIRED');
CREATE TYPE "AdmissionMediaRole" AS ENUM ('CALLER','OPERATOR_LISTENER','OPERATOR_SPEAKER');
CREATE TYPE "MediaControlKind" AS ENUM ('GRANT','REMOVE');
CREATE TYPE "MediaControlStatus" AS ENUM ('PENDING','RUNNING','CONFIRMED','FAILED');
CREATE TABLE "VoiceSession" ("id" TEXT PRIMARY KEY, "callId" TEXT NOT NULL REFERENCES "Call"("id") ON DELETE RESTRICT ON UPDATE CASCADE, "roomName" TEXT NOT NULL, "transport" "VoiceTransport" NOT NULL DEFAULT 'LIVEKIT', "ownerUserId" TEXT, "ownerSessionId" TEXT, "createRequestId" TEXT NOT NULL UNIQUE, "createRequestHash" TEXT NOT NULL, "dispatchIntentId" TEXT NOT NULL UNIQUE, "providerDispatchId" TEXT, "state" "VoiceSessionState" NOT NULL DEFAULT 'STARTING', "ownershipMode" "VoiceOwnershipMode" NOT NULL DEFAULT 'AI', "authorizationVersion" INTEGER NOT NULL DEFAULT 1, "currentEpoch" INTEGER NOT NULL DEFAULT 0, "finalWatermark" INTEGER NOT NULL DEFAULT 0, "transcriptComplete" BOOLEAN NOT NULL DEFAULT false, "version" INTEGER NOT NULL DEFAULT 1, "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "endedAt" TIMESTAMP(3), "expiresAt" TIMESTAMP(3), "language" TEXT NOT NULL DEFAULT 'hi', "prompt" TEXT NOT NULL DEFAULT '');
CREATE UNIQUE INDEX "VoiceSession_callId_roomName_key" ON "VoiceSession"("callId","roomName"); CREATE UNIQUE INDEX "VoiceSession_callId_key" ON "VoiceSession"("callId"); CREATE INDEX "VoiceSession_state_expiresAt_idx" ON "VoiceSession"("state","expiresAt");
CREATE TABLE "VoiceParticipant" ("id" TEXT PRIMARY KEY, "sessionId" TEXT NOT NULL REFERENCES "VoiceSession"("id") ON DELETE CASCADE ON UPDATE CASCADE, "identity" TEXT NOT NULL, "role" "Speaker" NOT NULL, "confirmedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE("sessionId","identity"));
CREATE TABLE "VoiceLease" ("id" TEXT PRIMARY KEY, "sessionId" TEXT NOT NULL UNIQUE REFERENCES "VoiceSession"("id") ON DELETE CASCADE ON UPDATE CASCADE, "agentEpoch" INTEGER NOT NULL, "tokenHash" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "renewedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE("sessionId","agentEpoch")); CREATE INDEX "VoiceLease_expiresAt_idx" ON "VoiceLease"("expiresAt");
CREATE TABLE "VoiceSessionUsage" ("sessionId" TEXT PRIMARY KEY REFERENCES "VoiceSession"("id") ON DELETE CASCADE ON UPDATE CASCADE, "events" INTEGER NOT NULL DEFAULT 0, "bytes" INTEGER NOT NULL DEFAULT 0);
CREATE TABLE "VoiceEvent" ("id" TEXT PRIMARY KEY, "sessionId" TEXT NOT NULL REFERENCES "VoiceSession"("id") ON DELETE CASCADE ON UPDATE CASCADE, "eventId" TEXT NOT NULL, "agentEpoch" INTEGER NOT NULL, "sourceSequence" INTEGER NOT NULL, "canonicalBody" TEXT NOT NULL, "bodyHash" TEXT NOT NULL, "type" TEXT NOT NULL, "occurredAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE("sessionId","eventId"), UNIQUE("sessionId","agentEpoch","sourceSequence"));
CREATE TABLE "TranscriptSegment" ("id" TEXT PRIMARY KEY, "sessionId" TEXT NOT NULL REFERENCES "VoiceSession"("id") ON DELETE CASCADE ON UPDATE CASCADE, "segmentId" TEXT NOT NULL, "revision" INTEGER NOT NULL, "speaker" "Speaker" NOT NULL, "participantId" TEXT NOT NULL, "sequence" INTEGER NOT NULL, "text" TEXT NOT NULL, "startMs" INTEGER, "endMs" INTEGER, "language" TEXT NOT NULL, "isCurrent" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE("sessionId","segmentId","revision")); CREATE INDEX "TranscriptSegment_sessionId_sequence_isCurrent_idx" ON "TranscriptSegment"("sessionId","sequence","isCurrent");
CREATE TABLE "VoiceAdmission" ("id" TEXT PRIMARY KEY, "callId" TEXT NOT NULL, "voiceSessionId" TEXT NOT NULL REFERENCES "VoiceSession"("id") ON DELETE CASCADE ON UPDATE CASCADE, "sessionId" TEXT NOT NULL, "userId" TEXT NOT NULL, "participantIdentity" TEXT NOT NULL UNIQUE, "participantSid" TEXT, "role" "AdmissionMediaRole" NOT NULL, "authorizationVersion" INTEGER NOT NULL, "state" "VoiceAdmissionState" NOT NULL DEFAULT 'ISSUED', "issuedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "firstJoinExpiresAt" TIMESTAMP(3) NOT NULL, "absoluteExpiresAt" TIMESTAMP(3) NOT NULL, "revokedAt" TIMESTAMP(3), "revokeReason" TEXT, "connectionEpoch" INTEGER NOT NULL DEFAULT 0, "connectionOwner" TEXT, "connectionLeaseExpiresAt" TIMESTAMP(3), "lastAuthorizedAt" TIMESTAMP(3)); CREATE INDEX "VoiceAdmission_callId_state_idx" ON "VoiceAdmission"("callId","state"); CREATE INDEX "VoiceAdmission_sessionId_state_idx" ON "VoiceAdmission"("sessionId","state");
CREATE TABLE "MediaControlIntent" ("id" TEXT PRIMARY KEY, "admissionId" TEXT NOT NULL REFERENCES "VoiceAdmission"("id") ON DELETE CASCADE ON UPDATE CASCADE, "authorizationVersion" INTEGER NOT NULL, "kind" "MediaControlKind" NOT NULL, "status" "MediaControlStatus" NOT NULL DEFAULT 'PENDING', "attemptToken" TEXT, "leaseExpiresAt" TIMESTAMP(3), "errorCode" TEXT, "attempts" INTEGER NOT NULL DEFAULT 0, "nextAttemptAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL); CREATE INDEX "MediaControlIntent_status_nextAttemptAt_idx" ON "MediaControlIntent"("status","nextAttemptAt"); CREATE INDEX "MediaControlIntent_admissionId_authorizationVersion_kind_idx" ON "MediaControlIntent"("admissionId","authorizationVersion","kind");
CREATE TABLE "ToolInvocation" ("id" TEXT PRIMARY KEY, "sessionId" TEXT NOT NULL REFERENCES "VoiceSession"("id") ON DELETE CASCADE ON UPDATE CASCADE, "invocationId" TEXT NOT NULL, "agentEpoch" INTEGER NOT NULL, "name" TEXT NOT NULL, "canonicalPayload" TEXT NOT NULL, "payloadHash" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "result" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE("sessionId","invocationId"));
