"""The create_business_request tool's arguments, derived from the API's request contract.

The worker image does not contain the contracts package, so the derived schema is
generated into request_tool_schema.py. Regenerate it after the contract changes:

    python -m madhusudan_voice.request_tool ../../packages/contracts/json-schema/demo-v1/create-request.json
"""

from __future__ import annotations

import json
import pprint
import sys
from pathlib import Path
from typing import Any

# Filled in by the API for every call; the model never supplies them.
SERVER_FIELDS = ("callId", "requestId")


def tool_parameters(create_request: dict[str, Any]) -> dict[str, Any]:
    """One branch per journey, with its confirmation kinds folded into one enum.

    That keeps each journey's exact fields while offering the model a third of the
    contract's size. The API still checks the full contract, including that only a
    follow-up names the request it follows.
    """
    journeys: dict[str, list[tuple[dict[str, Any], set[str]]]] = {}
    for branch in create_request["anyOf"]:
        properties = {key: value for key, value in branch["properties"].items() if key not in SERVER_FIELDS}
        required = {key for key in branch["required"] if key not in SERVER_FIELDS}
        journeys.setdefault(properties["journey"]["const"], []).append((properties, required))
    branches = []
    for journey, variants in journeys.items():
        properties: dict[str, Any] = {}
        for variant, _ in variants:
            for key, value in variant.items():
                if key == "callerConfirmation":
                    continue
                if key in properties and properties[key] != value:
                    raise ValueError(f"{journey}.{key} differs between confirmation kinds")
                properties[key] = value
        properties["callerConfirmation"] = {"type": "string", "enum": sorted(variant["callerConfirmation"]["const"] for variant, _ in variants)}
        # Only what every confirmation kind requires, so no valid request is refused here.
        required = set.intersection(*(required for _, required in variants))
        branch: dict[str, Any] = {
            "type": "object",
            "additionalProperties": False,
            "properties": dict(sorted(properties.items())),
            "required": sorted(required),
        }
        if "parentRequestId" in properties:
            branch["description"] = "Give parentRequestId only when callerConfirmation is FOLLOW_UP; a follow-up requires it."
        branches.append(branch)
    return {
        "type": "object",
        "additionalProperties": False,
        "properties": {"request": {"anyOf": branches}},
        "required": ["request"],
    }


def render(parameters: dict[str, Any]) -> str:
    return (
        '"""Generated by `python -m madhusudan_voice.request_tool` from the API\'s create-request\n'
        'contract; do not edit."""\n\n'
        "from typing import Any\n\n"
        f"TOOL_PARAMETERS: dict[str, Any] = {pprint.pformat(parameters, width=100, sort_dicts=False)}\n"
    )


if __name__ == "__main__":
    contract = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    Path(__file__).with_name("request_tool_schema.py").write_text(render(tool_parameters(contract)), encoding="utf-8")
